export const livePreviewBreakpoints = [
  {
    label: 'Samsung Galaxy S20',
    name: 'samsung-galaxy-s20',
    width: 360,
    height: 800,
  },
  {
    label: 'Google Pixel 5',
    name: 'google-pixel-5',
    width: 393,
    height: 851,
  },
  {
    label: 'Oneplus Nord 2',
    name: 'oneplus-nord-2',
    width: 412,
    height: 915,
  },
  {
    label: 'Galaxy Z Flip3',
    name: 'galaxy-z-flip3',
    width: 360,
    height: 880,
  },
  {
    label: 'OPPO Find X3 PRO',
    name: 'oppo-find-x3-pro',
    width: 360,
    height: 804,
  },
  {
    label: 'Google Pixel 6 PRO',
    name: 'google-pixel-6-pro',
    width: 360,
    height: 780,
  },
  {
    label: 'Galaxy Note20 Ultra',
    name: 'galaxy-note20-ultra',
    width: 412,
    height: 883,
  },
  {
    label: 'Galaxy S22 Ultra',
    name: 'galaxy-s22-ultra',
    width: 360,
    height: 772,
  },
  {
    label: 'Google Pixel 8',
    name: 'google-pixel-8',
    width: 412,
    height: 916,
  },
  {
    label: 'Galaxy S24 ULTRA',
    name: 'galaxy-s24-ultra',
    width: 384,
    height: 832,
  },
  {
    label: 'iPhone 5',
    name: 'iphone-5',
    width: 320,
    height: 568,
  },
  {
    label: 'iPhone 11',
    name: 'iphone-11',
    width: 414,
    height: 896,
  },
  {
    label: 'iPhone 11 PRO',
    name: 'iphone-11-pro',
    width: 375,
    height: 812,
  },
  {
    label: 'iPhone 11 PRO MAX',
    name: 'iphone-11-pro-max',
    width: 414,
    height: 896,
  },
  {
    label: 'iPhone 12 PRO',
    name: 'iphone-12-pro',
    width: 390,
    height: 884,
  },
  {
    label: 'iPhone 14 Plus',
    name: 'iphone-14-plus',
    width: 428,
    height: 926,
  },
  {
    label: 'iPhone 14 PRO',
    name: 'iphone-14-pro',
    width: 390,
    height: 844,
  },
  {
    label: 'iPhone 14 PRO MAX',
    name: 'iphone-14-pro-max',
    width: 428,
    height: 928,
  },
  {
    label: 'iPhone 16 (iOS 18)',
    name: 'iphone-16-(ios-18)',
    width: 393,
    height: 852,
  },
  {
    label: 'iPhone 16 Plus',
    name: 'iphone-16-plus',
    width: 430,
    height: 932,
  },
  {
    label: 'iPhone 16 PRO MAX',
    name: 'iphone-16-pro-max',
    width: 440,
    height: 956,
  },
  {
    label: 'iPad Mini',
    name: 'ipad-mini',
    width: 768,
    height: 1024,
  },
  {
    label: 'iPad Air 4',
    name: 'ipad-air-4',
    width: 820,
    height: 1180,
  },
  {
    label: 'iPad PRO 11',
    name: 'ipad-pro-11',
    width: 834,
    height: 1194,
  },
  {
    label: 'Galaxy Tab S7',
    name: 'galaxy-tab-s7',
    width: 800,
    height: 1280,
  },
  {
    label: 'Galaxy Fold2',
    name: 'galaxy-fold2',
    width: 884,
    height: 1104,
  },
  {
    label: 'Macbook Air',
    name: 'macbook-air',
    width: 1280,
    height: 800,
  },
  {
    label: 'Dell Latitude',
    name: 'dell-latitude',
    width: 1440,
    height: 809,
  },
  {
    label: 'Macbook PRO 16 2021',
    name: 'macbook-pro-16-2021',
    width: 1728,
    height: 1085,
  },
  {
    label: 'Samsung Smart TV',
    name: 'samsung-smart-tv',
    width: 1920,
    height: 1080,
  },
]